name: Mobs
version: 1.0.2
main: tgwaste\Mobs\Main
api: 4.0.0
author: tgwaste
commands:
  killmobs:
    usage: "/killmobs"
    description: "Kill all Mobs"
  listmobs:
    usage: "/listmobs"
    description: "List all Mobs"
  summon:
    usage: "/summon <type>"
    description: "Summon a Mob"
