name: Mobs
version: 1.1.0
main: tgwaste\Mobs\Main
api: 4.0.0
author: tgwaste
commands:
  killmobs:

    usage: "/killmobs"
    description: "Kill all Mobs"
    permission: pocketmine.group.operator
  listmobs:
    usage: "/listmobs"
    description: "List all Mobs"
    permission: pocketmine.group.operator
  summon:
    usage: "/summon <type> [quantity]"
    description: "Summon a Mob"
    permission: pocketmine.group.operator
