---
# whether mobs spawn at all
spawnmobs: true
# write spawn/despawn messages to the console
# this is noisy and mostly for debugging
spawnmsgs: false
# show name tags and health percent if percent is less than 100
damagetags: true
# regain this much health over time when idle
# setting to 0 disables
regainhealth: 1
# mobs will not spawn in any worldname containing one of these strings
nospawn:
- arena
- lobby
# amount of mobs to spawn of each type (higher numbers will use a lot more system resources)
Bat: 3
Blaze: 3
Cat: 3
CaveSpider: 3
Chicken: 3
Cod: 3
Cow: 3
Creeper: 3
Dolphin: 3
Enderman: 3
Horse: 3
Husk: 3
MagmaCube: 3
Mooshroom: 3
Parrot: 3
Phantom: 3
Pig: 3
PolarBear: 3
PufferFish: 3
Rabbit: 3
Salmon: 3
Sheep: 3
Skeleton: 3
Slime: 3
Spider: 3
Squid: 3
Stray: 3
TropicalFish: 3
Villager: 3
Wolf: 3
Zombie: 3
...
